2025-07-28 09:59:58,937 ERROR: Error on request:
Traceback (most recent call last):
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 808, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\mindai\backend\app.py", line 229, in chatbot_feedback
    return render_template('chatbot_feedback.html')
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: chatbot_feedback.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1417, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 715, in handle_user_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\mindai\backend\app.py", line 127, in handle_exception
    return render_template('500.html', error_message=str(e)), 500 # 500.htmlÀÌ ¾øÀ¸¹Ç·Î ÀÓ½Ã·Î ¿¡·¯ ¸Þ½ÃÁö Á÷Á¢ Ç¥½Ã
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 500.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1442, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1420, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 766, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\mindai\backend\app.py", line 127, in handle_exception
    return render_template('500.html', error_message=str(e)), 500 # 500.htmlÀÌ ¾øÀ¸¹Ç·Î ÀÓ½Ã·Î ¿¡·¯ ¸Þ½ÃÁö Á÷Á¢ Ç¥½Ã
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 500.html
2025-07-28 10:00:01,632 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:01] "[36mGET /static/css/base.css HTTP/1.1[0m" 304 -
2025-07-28 10:00:01,632 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:01] "[36mGET /static/css/admin_dashboard.css HTTP/1.1[0m" 304 -
2025-07-28 10:00:04,449 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET / HTTP/1.1" 200 -
2025-07-28 10:00:04,481 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET /static/css/base.css HTTP/1.1" 200 -
2025-07-28 10:00:04,484 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET /static/css/index.css HTTP/1.1" 200 -
2025-07-28 10:00:04,487 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET /static/images/main_logo.png HTTP/1.1" 200 -
2025-07-28 10:00:04,849 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET /api/auth/me HTTP/1.1" 200 -
2025-07-28 10:00:04,855 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET /api/dashboard/stats HTTP/1.1" 200 -
2025-07-28 10:00:04,869 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:04] "GET /api/admin/menu_items/my_menu HTTP/1.1" 200 -
2025-07-28 10:00:07,838 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:07] "GET /login HTTP/1.1" 200 -
2025-07-28 10:00:07,883 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:07] "GET /static/css/base.css HTTP/1.1" 200 -
2025-07-28 10:00:07,893 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:07] "GET /static/css/login_signup.css HTTP/1.1" 200 -
2025-07-28 10:00:07,894 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:07] "GET /static/images/main_logo.png HTTP/1.1" 200 -
2025-07-28 10:00:10,375 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:10] "GET /signup HTTP/1.1" 200 -
2025-07-28 10:00:10,410 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:10] "GET /static/css/base.css HTTP/1.1" 200 -
2025-07-28 10:00:10,421 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:10] "GET /static/css/login_signup.css HTTP/1.1" 200 -
2025-07-28 10:00:10,421 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:10] "GET /static/images/main_logo.png HTTP/1.1" 200 -
2025-07-28 10:00:35,423 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:35] "GET /signup HTTP/1.1" 200 -
2025-07-28 10:00:35,470 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:35] "GET /static/css/base.css HTTP/1.1" 200 -
2025-07-28 10:00:35,478 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:35] "GET /static/css/login_signup.css HTTP/1.1" 200 -
2025-07-28 10:00:35,479 INFO: 127.0.0.1 - - [28/Jul/2025 10:00:35] "GET /static/images/main_logo.png HTTP/1.1" 200 -
2025-07-28 10:03:12,879 INFO: 127.0.0.1 - - [28/Jul/2025 10:03:12] "GET /signup HTTP/1.1" 200 -
2025-07-28 10:03:12,896 INFO: 127.0.0.1 - - [28/Jul/2025 10:03:12] "GET /static/css/base.css HTTP/1.1" 200 -
2025-07-28 10:03:12,900 INFO: 127.0.0.1 - - [28/Jul/2025 10:03:12] "GET /static/images/main_logo.png HTTP/1.1" 200 -
