<<<<<<< HEAD
2025-07-25 09:54:26,163 INFO: Request: GET /static/images/main_logo.png [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,279 INFO: Response: GET /static/css/base.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,283 INFO: Response: GET /static/images/main_logo.png 200 [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,762 INFO: Request: GET /api/diary/entries/month_summary [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,763 INFO: Request: GET /api/auth/check_auth [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,793 INFO: Response: GET /api/auth/check_auth 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,801 INFO: Request: GET /api/admin/menu_items/my_menu [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,807 INFO: DEBUG (get_my_menu_items): API called. Attempting to find menus for roles: ['관리자'] [in C:\mindai\backend\routes\admin_routes.py:154]
2025-07-25 09:54:26,809 INFO: Response: GET /api/diary/entries/month_summary 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,810 WARNING: DEBUG (get_my_menu_items): Found role assignments, but no menu IDs were associated. Returning empty list. [in C:\mindai\backend\routes\admin_routes.py:173]
2025-07-25 09:54:26,812 INFO: Response: GET /api/admin/menu_items/my_menu 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:02:19,745 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:02:20,238 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:02:21,261 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:02:21,268 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:46,394 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:03:46,904 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:03:49,158 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:49,165 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,223 INFO: Request: GET / [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,234 INFO: Response: GET / 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,260 INFO: Request: GET /static/css/base.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,262 INFO: Request: GET /static/css/index.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,263 INFO: Request: GET /static/images/main_logo.png [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,447 INFO: Response: GET /static/images/main_logo.png 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,447 INFO: Response: GET /static/css/index.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,452 INFO: Response: GET /static/css/base.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,844 INFO: Request: GET /api/dashboard/stats [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,845 INFO: Request: GET /api/auth/check_auth [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,884 INFO: Response: GET /api/auth/check_auth 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,896 INFO: Request: GET /api/admin/menu_items/my_menu [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,911 INFO: DEBUG (get_my_menu_items): API called. Attempting to find menus for roles: ['관리자'] [in C:\mindai\backend\routes\admin_routes.py:154]
2025-07-25 10:03:58,915 INFO: Response: GET /api/dashboard/stats 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,920 WARNING: DEBUG (get_my_menu_items): Found role assignments, but no menu IDs were associated. Returning empty list. [in C:\mindai\backend\routes\admin_routes.py:173]
2025-07-25 10:03:58,922 INFO: Response: GET /api/admin/menu_items/my_menu 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:52,093 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:05:52,616 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:05:54,053 INFO: Request: GET / [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,063 INFO: Response: GET / 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,104 INFO: Request: GET /static/css/base.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,118 INFO: Request: GET /static/css/index.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,119 INFO: Request: GET /static/images/main_logo.png [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,265 INFO: Response: GET /static/css/base.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,282 INFO: Response: GET /static/css/index.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,282 INFO: Response: GET /static/images/main_logo.png 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,684 INFO: Request: GET /api/dashboard/stats [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,684 INFO: Request: GET /api/auth/check_auth [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,730 INFO: Response: GET /api/auth/check_auth 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,744 INFO: Request: GET /api/admin/menu_items/my_menu [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,751 INFO: DEBUG (get_my_menu_items): API called. Attempting to find menus for roles: ['관리자'] [in C:\mindai\backend\routes\admin_routes.py:154]
2025-07-25 10:05:54,753 INFO: Response: GET /api/dashboard/stats 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,757 WARNING: DEBUG (get_my_menu_items): Found role assignments, but no menu IDs were associated. Returning empty list. [in C:\mindai\backend\routes\admin_routes.py:173]
2025-07-25 10:05:54,758 INFO: Response: GET /api/admin/menu_items/my_menu 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:05,132 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:05,137 ERROR: An unhandled exception occurred: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\mindai\backend\app.py:123]
Traceback (most recent call last):
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 808, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\mindai\backend\app.py", line 166, in diary
    return render_template('diary.html')
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\mindai\frontend\templates\diary.html", line 13, in template
    <div class="diary-content-wrapper-outer" id="diaryContentWrapperOuter"> {# 전체 일기 콘텐츠를 감싸는 래퍼 #}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-07-25 10:06:05,152 INFO: Response: GET /diary 500 [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:06,672 INFO: Request: GET /static/css/base.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:06,673 INFO: Request: GET /static/css/index.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:06,674 INFO: Response: GET /static/css/base.css 304 [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:06,675 INFO: Response: GET /static/css/index.css 304 [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:21,218 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:06:21,742 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:06:27,310 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:27,318 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:10:00,604 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:10:01,090 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:10:02,371 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:10:02,379 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
=======
2025-07-25 09:54:26,163 INFO: Request: GET /static/images/main_logo.png [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,279 INFO: Response: GET /static/css/base.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,283 INFO: Response: GET /static/images/main_logo.png 200 [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,762 INFO: Request: GET /api/diary/entries/month_summary [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,763 INFO: Request: GET /api/auth/check_auth [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,793 INFO: Response: GET /api/auth/check_auth 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,801 INFO: Request: GET /api/admin/menu_items/my_menu [in C:\mindai\backend\app.py:95]
2025-07-25 09:54:26,807 INFO: DEBUG (get_my_menu_items): API called. Attempting to find menus for roles: ['관리자'] [in C:\mindai\backend\routes\admin_routes.py:154]
2025-07-25 09:54:26,809 INFO: Response: GET /api/diary/entries/month_summary 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 09:54:26,810 WARNING: DEBUG (get_my_menu_items): Found role assignments, but no menu IDs were associated. Returning empty list. [in C:\mindai\backend\routes\admin_routes.py:173]
2025-07-25 09:54:26,812 INFO: Response: GET /api/admin/menu_items/my_menu 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:02:19,745 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:02:20,238 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:02:21,261 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:02:21,268 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:46,394 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:03:46,904 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:03:49,158 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:49,165 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,223 INFO: Request: GET / [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,234 INFO: Response: GET / 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,260 INFO: Request: GET /static/css/base.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,262 INFO: Request: GET /static/css/index.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,263 INFO: Request: GET /static/images/main_logo.png [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,447 INFO: Response: GET /static/images/main_logo.png 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,447 INFO: Response: GET /static/css/index.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,452 INFO: Response: GET /static/css/base.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,844 INFO: Request: GET /api/dashboard/stats [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,845 INFO: Request: GET /api/auth/check_auth [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,884 INFO: Response: GET /api/auth/check_auth 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,896 INFO: Request: GET /api/admin/menu_items/my_menu [in C:\mindai\backend\app.py:95]
2025-07-25 10:03:58,911 INFO: DEBUG (get_my_menu_items): API called. Attempting to find menus for roles: ['관리자'] [in C:\mindai\backend\routes\admin_routes.py:154]
2025-07-25 10:03:58,915 INFO: Response: GET /api/dashboard/stats 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:03:58,920 WARNING: DEBUG (get_my_menu_items): Found role assignments, but no menu IDs were associated. Returning empty list. [in C:\mindai\backend\routes\admin_routes.py:173]
2025-07-25 10:03:58,922 INFO: Response: GET /api/admin/menu_items/my_menu 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:52,093 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:05:52,616 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:05:54,053 INFO: Request: GET / [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,063 INFO: Response: GET / 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,104 INFO: Request: GET /static/css/base.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,118 INFO: Request: GET /static/css/index.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,119 INFO: Request: GET /static/images/main_logo.png [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,265 INFO: Response: GET /static/css/base.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,282 INFO: Response: GET /static/css/index.css 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,282 INFO: Response: GET /static/images/main_logo.png 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,684 INFO: Request: GET /api/dashboard/stats [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,684 INFO: Request: GET /api/auth/check_auth [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,730 INFO: Response: GET /api/auth/check_auth 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,744 INFO: Request: GET /api/admin/menu_items/my_menu [in C:\mindai\backend\app.py:95]
2025-07-25 10:05:54,751 INFO: DEBUG (get_my_menu_items): API called. Attempting to find menus for roles: ['관리자'] [in C:\mindai\backend\routes\admin_routes.py:154]
2025-07-25 10:05:54,753 INFO: Response: GET /api/dashboard/stats 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:05:54,757 WARNING: DEBUG (get_my_menu_items): Found role assignments, but no menu IDs were associated. Returning empty list. [in C:\mindai\backend\routes\admin_routes.py:173]
2025-07-25 10:05:54,758 INFO: Response: GET /api/admin/menu_items/my_menu 200 user_id=1 username=admin [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:05,132 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:05,137 ERROR: An unhandled exception occurred: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\mindai\backend\app.py:123]
Traceback (most recent call last):
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 808, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\mindai\backend\app.py", line 166, in diary
    return render_template('diary.html')
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ADsThinkCentre\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\mindai\frontend\templates\diary.html", line 13, in template
    <div class="diary-content-wrapper-outer" id="diaryContentWrapperOuter"> {# 전체 일기 콘텐츠를 감싸는 래퍼 #}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-07-25 10:06:05,152 INFO: Response: GET /diary 500 [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:06,672 INFO: Request: GET /static/css/base.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:06,673 INFO: Request: GET /static/css/index.css [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:06,674 INFO: Response: GET /static/css/base.css 304 [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:06,675 INFO: Response: GET /static/css/index.css 304 [in C:\mindai\backend\app.py:106]
2025-07-25 10:06:21,218 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:06:21,742 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:06:27,310 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:06:27,318 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
2025-07-25 10:10:00,604 INFO: Flask app created [in C:\mindai\backend\app.py:63]
2025-07-25 10:10:01,090 INFO: ADMIN UPLOAD_FOLDER already exists: C:\mindai\backend\routes\..\..\frontend\static\uploads\admin [in C:\mindai\backend\routes\admin_routes.py:24]
2025-07-25 10:10:02,371 INFO: Request: GET /diary [in C:\mindai\backend\app.py:95]
2025-07-25 10:10:02,379 INFO: Response: GET /diary 200 [in C:\mindai\backend\app.py:106]
>>>>>>> 32e57f7623365b93a09d34dc9cad501cc18c11af
